<a href="https://colab.research.google.com/github/fernandodeeke/can2025/blob/main/gauss_elim_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center><h1></h1></center>
<center><h1>Análise Numérica</h1></center>
<center><h2>2025/1</h2></center>
<center><h3>Eliminação Gaussiana - Parte 2</h3></center>
<center><h4>Prof. Fernando Deeke Sasse - CCT, UDESC</h4></center>
<center><h3>2025</h3></center>

### 1. Eliminação gaussiana simples - Revisão

Já descrevemos anteriormente as operações elementares de linha, essenciais no processo de eliminação gaussiana simples. Nosso objetivo agora é automatizar o processo definindo uma função em Python capaz de realizar essas etapas de uma só vez. Consideraremos novamente um [sistema linear](https://pt.wikipedia.org/wiki/Sistema_de_equações_lineares) com $n$ equações e $n$ incógnitas para as variáveis $x_1,\ldots, x_n$, da forma:

\begin{align}
a_{11}x_1 + a_{12}x_2 + \cdots + a_{1n}x_n & = b_1 \\\
a_{21}x_1 + a_{22}x_2 + \cdots + a_{2n}x_n & = b_2 \\\
& \vdots \\\
a_{n1}x_1 + a_{m1}x_2 + \cdots + a_{nn}x_n & = b_n
\end{align}

 Em notação matricial o sistema linear é representado na forma
 $A X= B$, sendo

$$
A = \begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\\
a_{21} & a_{22} & \cdots & a_{2n} \\\
\vdots & & & \vdots \\\
a_{n1} & a_{n2} & \cdots & a_{nn}
\end{bmatrix}
 \ \ , \ \
X = \begin{bmatrix}
x_1 \\\ x_2 \\\ \vdots \\\ x_n
\end{bmatrix}
 \ \ , \ \
B = \begin{bmatrix}
b_1 \\\ b_2 \\\ \vdots \\\ b_n
\end{bmatrix}
$$

O chamado método da eliminação gaussiana simples é o método direto mais utilizado para resolver sistemas lineares e é a base para todas as variantes de métodos de eliminação. Ele consiste de duas etapas:

1. Fase de eliminação: realizamos a eliminação dos elementos abaixo da diagonal principal da matriz ampliada $[A|B]$ por meio de transformações elementares sobre matrizes, até obtermos a forma escalonada.
2. Retrosubstituição.

Descreveremos a seguir cada uma destas etapas, já definindo uma função em Python que realizada cada etapa:

### 2. Fase de eliminação
Chamamos *linha pivot* a linha acima da qual todos os elementos abaixo da diagonal principal já foram zerados.
Na matriz ampliada, seja a  linha pivot $L_k$ e uma típica linha $L_i$ abaixo a ser transformada, de modo a zerar o elemento $a_{ik}$. Para isso devemos multiplicar a linha pivot  por $\lambda = a_{ik}/a_{kk}$ e subtrair o resultado de $L_i$, ou seja,

$$
L_i \rightarrow L_i - \lambda L_k\,.
$$

Os elementos da linha $L_i$ são atualizados da seguinte forma:

\begin{align}
&a_{ij} \leftarrow a_{ij} - \lambda a_{kj}\,\qquad j=k, \ldots , n\\
&b_i \leftarrow b_i - \lambda b_k\,.
\end{align}

Como $a_{ik}=0$ por construção, para economizar tempo computacional, ele não precisa ser calculado, de modo podemos tomar $j=k+1, \ldots , n$.

O índice $k$ é  o índice da linha pivot, de modo que $k=1,  \ldots, n-1$ O índice $i$ designa a linha a ser transformada, de modo que $i=k+1,\ldots, n$.

É conveniente lembrar o modo de indexação do Python. O primeiro índice é zero:

In [ ]:
import numpy as np

In [ ]:
c=np.array([1,2,3,4])
c

array([1, 2, 3, 4])

In [ ]:
c[0]

1

In [ ]:
c[3]

4

Quando usamos range(i,j), o valor de j não é incluído. Por exemplo,

In [ ]:
for j in range(0,3):
    print(c[j])

1
2
3


Notemos que c[3] não foi selecionado.

O elemento c definido acima é formalmente um array 1-dimensional, ou uma matriz com somente uma linha. Seu comprimento é o número de elementos:

In [ ]:
len(c)

4

Se tentarmos calcular a transposta de c usando um comando de atribuição, não haverá efeito:  

In [ ]:
np.transpose(c)

array([1, 2, 3, 4])

Podemos usar a alternativa:

In [ ]:
cT = np.transpose([c])
cT

array([[1],
       [2],
       [3],
       [4]])

Notemos que

In [ ]:
len(cT)

4

Alternativamente poderíamos ter definido:

In [ ]:
c = np.array([[2,3,4,5]])
c

array([[2, 3, 4, 5]])

de modo que

In [ ]:
c.T

array([[2],
       [3],
       [4],
       [5]])

Para uma matriz, o comprimento é número de linhas (listas) que ela contém:

In [ ]:
M = np.array([[2,3,4], [3, 4, 5], [2, 3, 7], [3, 4, 1]])
M

array([[2, 3, 4],
       [3, 4, 5],
       [2, 3, 7],
       [3, 4, 1]])

In [ ]:
len(M)

4

O algoritmo  de eliminação pode ser realizado em Python da seguinte forma:

In [ ]:
def GaussElimin(a,b):
    n = len(a)
    for k in range(0,n-1): # Define o índice do elemento pivot (0,1,2 para n = 4)
        for i in range(k+1,n): # Percorre a linha abaixo da linha do pivot e vai até a linha n-1 (3 para n=4)
            lam = a[i,k]/a[k,k]
            a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n] # Atualiza os elementos da linha i
            a[i,k]=0
            b[i] = b[i] - lam*b[k]
    return  np.hstack([a,b])

Testemos a função.

In [ ]:
A = np.array([[6.,1.,2.,4.],[5.,11.,-3.,2.],[-3.,4.,3.,5.],[5.,2.,8.,3.]])
print(A)

[[ 6.  1.  2.  4.]
 [ 5. 11. -3.  2.]
 [-3.  4.  3.  5.]
 [ 5.  2.  8.  3.]]


In [ ]:
B = np.transpose(np.array([[2.,-4.,3.,-7.]]))
print(B)

[[ 2.]
 [-4.]
 [ 3.]
 [-7.]]


É importante notar que as os números dados nas entradas são terminados por um ponto, para informa que ele é do tipo *float* e não *integer*. Outra opção seria usar uma entrada da forma:

In [ ]:
A = np.array([[6,1,2,4],[5,11,-3,2],[-3,4,3,5],[5,2,8,3]],dtype=float)
B = np.transpose(np.array([[2,-4,3,-7]],dtype=float))

 Formemos a matriz aumentada $M$:

In [ ]:
M = np.hstack([A,B])
print(M)

[[ 6.  1.  2.  4.  2.]
 [ 5. 11. -3.  2. -4.]
 [-3.  4.  3.  5.  3.]
 [ 5.  2.  8.  3. -7.]]


Realizemos a eliminação gaussiana:

In [ ]:
M1=GaussElimin(A,B)
print(M1)

[[  6.           1.           2.           4.           2.        ]
 [  0.          10.16666667  -4.66666667  -1.33333333  -5.66666667]
 [  0.           0.           6.06557377   7.59016393   6.50819672]
 [  0.           0.           0.          -8.77567568 -15.38648649]]


### 3.  Fase de retrosubstituição

Começamos a resolver a corresponde última equação do sistema reduzido, ou seja,

$$
x_n=\frac{b_n}{a_{nn}}\,.
$$

Consideremos agora o estágio da retrosubstituição onde $x_n, x_{n-1}, \ldots , x_{k+1} $ já foram computados e devemos computar $x_k$ a partir da equação $k$:

$$
a_{kk}x_k+a_{k k+1} x_{k+1}+ \cdots + a_{k n}x_n=b_k\,.
$$

Resolvendo para $k_k$ obtemos

$$
x_k=\frac{1}{a_{kk}}\left(b_k-a_{k k+1} x_{k+1}- \cdots - a_{k n}x_n\right)= \frac{1}{a_{kk}}\left(b_k-\sum_{j=k+1}^n a_{kj}x_j\right)\,.
$$

Implementemos esta função no Python.

A seguinte função tem como entrada uma matriz de coeficientes na forma escalonada e a matriz coluna da parte homogênea. A saída é solução do correspondente sistema linear.

In [ ]:
# Retrosubstituição
def GaussRetro(a,b):
    n = len(b)
    x=np.zeros(n)
    x[n-1]=b[n-1]/a[n-1,n-1]
    for k in range(n-1,-1,-1):
        x[k] = (b[k] - np.dot(a[k,k+1:n],x[k+1:n]))/a[k,k]
    return np.transpose([x])

Para entender o uso do comando np.dot acima devemos notar que para cada $k$, tanto $a[k,k+1:n]$ quanto $b[k+1:n]$ são vetores computacionais de comprimento $n-k$. O comando np.dot faz com que as respectivas componentes sejam multiplicadas e somadas, tal como no produto escalar usual. O comando range(n-1,-1,-1) faz com que os valores de k comecem em n-1 e sigam de modo descrescente até chegar em k=0 (que antecede -1).

 Usemos o exemplo acima. Inicialmente fatiamos a matriz ampliada. A matriz de coeficientes é dada por

In [ ]:
A1 = M1[:,0:4]
A1

array([[ 6.        ,  1.        ,  2.        ,  4.        ],
       [ 0.        , 10.16666667, -4.66666667, -1.33333333],
       [ 0.        ,  0.        ,  6.06557377,  7.59016393],
       [ 0.        ,  0.        ,  0.        , -8.77567568]])

A parte não homogênea é dada por:

In [ ]:
B1= M1[:,4]
B1

array([  2.        ,  -5.66666667,   6.50819672, -15.38648649])

Apliquemos agora a função que realiza a retrosubstituição:

In [ ]:
X1 = GaussRetro(A1,B1)
X1

array([[-0.32152756],
       [-0.84200801],
       [-1.1210348 ],
       [ 1.75331075]])

Podemos verificar que este resultado é correto. É importante definir novamente o sistema original, uma vez que as matrizes A e B foram modificadas ao longo do processo. Este procedimento é fundamental em Python.

In [ ]:
A = np.array([[6.,1.,2.,4.],[5.,11.,-3.,2.],[-3.,4.,3.,5.],[5.,2.,8.,3.]])
B = np.transpose(np.array([[2.,-4.,3.,-7.]]))

In [ ]:
A@X1-B

array([[-4.44089210e-16],
       [-8.88178420e-16],
       [ 8.88178420e-16],
       [-3.55271368e-15]])

Podemos resolver sistemas lineares com métodos diretos usando  comando solve do numpy:

In [ ]:
import numpy.linalg as la

In [ ]:
x = la.solve(A,B)
print(x)

[[-0.32152756]
 [-0.84200801]
 [-1.1210348 ]
 [ 1.75331075]]


### 4.  Algoritmo de eliminação gaussiana simples completo

Juntemos as duas funções numa só. A atribuição a[i,k]=0 agora pode ser removida pois é irrelevante:

In [ ]:
def GaussSolve(a,b):
    n = len(a)
    x=np.zeros(n)
    for k in range(0,n-1):
        for i in range(k+1,n):
            lam = a[i,k]/a[k,k]
            a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
            b[i] = b[i] - lam*b[k]
    x[n-1]=b[n-1]/a[n-1,n-1]
    for k in range(n-2,-1,-1):
        x[k] = (b[k] - np.dot(a[k,k+1:n],x[k+1:n]))/a[k,k]
    return np.transpose([x])

Testemos o algoritmo completo no sistema linear anterior.

In [ ]:
A = np.array([[6.,1.,2.,4.],[5.,11.,-3.,2.],[-3.,4.,3.,5.],[5.,2.,8.,3.]])
B = np.transpose(np.array([[2.,-4.,3.,-7.]]))

In [ ]:
X1=  GaussSolve(A,B)
X1

array([[-0.32152756],
       [-0.84200801],
       [-1.1210348 ],
       [ 1.75331075]])

que é o mesmo resultado obtido anteriormente

### 5. Exemplo com sistemas grandes

In [ ]:
Façamos testes em sistemas grandes aleatórios

In [ ]:
np.random.seed(43453)
N = 10
A3 = np.random.rand(N,N)
B3 = np.random.rand(N,1)

In [ ]:
X3 = GaussSolve(A3,B3)
X3

array([[-0.78014194],
       [ 1.64411949],
       [-1.13319994],
       [-0.72833755],
       [-2.02054919],
       [ 1.06249775],
       [-0.78987105],
       [ 2.26036594],
       [ 2.07989874],
       [-0.4584725 ]])

Verifiquemos a resposta, calculando o resíduo:

In [ ]:
np.random.seed(43453)
N = 10
A3 = np.random.rand(N,N)
B3 = np.random.rand(N,1)

In [ ]:
R=A3@X3-B3
R

array([[ 2.22044605e-16],
       [-5.55111512e-17],
       [-2.33146835e-15],
       [-6.38378239e-15],
       [-2.44249065e-15],
       [ 1.11022302e-15],
       [-2.77555756e-16],
       [-6.66133815e-15],
       [-5.21804822e-15],
       [-1.22124533e-15]])

Se o sistema é muito grande é difícil inspecionar todas as componentes. Em geral avaliamos o resíduo calculando uma norma do vetor correspondente. A norma mais usada é a norma infinito, é definida como sendo a maior magnitude entre as componentes:  

$$
|\mathbf{u}|_{\infty}=\max_i\{{|u_i|},i=1,\ldots,n\}.
$$

No nosso caso,

In [ ]:
import numpy.linalg as la

In [ ]:
NR = la.norm(R, np.inf)
NR

6.661338147750939e-15

Testemos o desempenho do programa que escrevemos com sistemas grandes.

In [ ]:
np.random.seed(43453)
N = 300
A4 = np.random.rand(N,N)
B4 = np.random.rand(N,1)

In [ ]:
X4 = GaussSolve(A4,B4)

Calculemos o resíduo:

In [ ]:
np.random.seed(43453)
N = 300
A4 = np.random.rand(N,N)
B4 = np.random.rand(N,1)

In [ ]:
NR = la.norm(A4@X4-B4,np.inf)
NR

6.33038066411018e-12

Examinemos o tempo de CPU necessário para resolver este sistema:

In [ ]:
np.random.seed(43453)
N = 300
A4 = np.random.rand(N,N)
B4 = np.random.rand(N,1)

In [ ]:
%%timeit
GaussSolve(A4,B4)

277 ms ± 1.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


O tempo de CPU necessário usando a função solve do numpy é dado por:

In [ ]:
np.random.seed(43453)
N = 300
A4 = np.random.rand(N,N)
B4 = np.random.rand(N,1)

In [ ]:
%%timeit
la.solve(A,B)

7.15 µs ± 78.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Como esperado, o solver é muito mais rápido do que nosso algoritmo pedagógico, por uma ordem de:

In [ ]:
277*10**(-3)/(7.15*10**(-6))

38741.258741258745

### 6. Exercícios

1. Resolva passo a passo um sistema linear $4 \times 4$ aleatório (use os 4 primeiros dígitos do seu cpf para o seed), descrevendo cada passo do algoritmo GaussElimin e GaussRetro. Verifique a resposta calculando o resíduo.
<p>
2. Resolva um sistema aleatório $500 \times 500$ usando o algoritmo GaussSolve (não mostre o resultado). Verifique a correção do resultado calculando a norma do resíduo e compare o tempo de CPU necessário. Repita o procedimento usando o solver do numpy.

3. A matriz de Hilbert $ H_n $ de ordem $ n $ é definida como:
$$
H_{ij} = \frac{1}{i + j + 1}, \quad i, j = 0, 1, \dots, n.
$$

Podemos defini-la no Python da seguinte forma:

In [7]:
def hilb(n):
    return np.array([[1/(i+j+1) for i in range(n)] for j in range(n)])

Por exemplo,

In [8]:
hilb(4)

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.33333333, 0.25      , 0.2       , 0.16666667],
       [0.25      , 0.2       , 0.16666667, 0.14285714]])

Matrizes de Hilbert são um clássico de exemplo de matrizes denominadas ma- condicionadas , no sentido de que pequenas perturbações na entrada geram soluções muito diferentes. O **número de condição** de uma matriz $ A $, denotado por $ \kappa(A) $, mede a sensibilidade da solução de um sistema linear $ A \mathbf{x} = \mathbf{b} $ a tais pequenas perturbações na matriz $ A $ ou no vetor $ \mathbf{b} $. Ele é definido como:
$$
\kappa(A) = \|A\| \cdot \|A^{-1}\|,
$$
onde $ \|A\| $ é a norma da matriz (normalmente a norma 2). Um número de condição alto indica que o sistema é mal condicionado, ou seja, pequenas mudanças nos dados podem causar grandes variações na solução.

(i) Resolva o sistema linear $HX=B$, sendo $H$ a matriz de Hilbert 30 x 30 e B uma matriz coluna formada por 1. Use o algoritmo desenvolvido anteriormente para resolver o sistema.  Calcule o resíduo em ambos os casos.

(ii) Estude a instabilidade de sistemas com matrizes de Hilbert $n \times n$. Por exemplo, varie um pouco o valor de um coeficiente de B, ou adicione um pequeno termo na matriz H.

(iii) Defina um sistema $GX=B$, $n \times n$, com $G=[g_{ij}]$ e $g_{ij}=1/(1+i+2j)$. Verifique se tal sistema também é instável. Varie $n$. Use o solver no Numpy, por exemplo,

In [9]:
# Calculando o número de condição
condicao = np.linalg.cond(hilb(4))
print(f"Número de condição da matriz de Hilbert: {cond_H}")

Número de condição da matriz de Hilbert: 15513.73873892924


In [2]:
### Código Inicial
import numpy as np
from scipy.linalg import hilbert

# Definindo a matriz de Hilbert
n = 10
H = hilbert(n)
b = np.ones(n)

# Calculando o número de condição
cond_H = np.linalg.cond(H)
print(f"Número de condição da matriz de Hilbert: {cond_H}")

Número de condição da matriz de Hilbert: 16024416987428.36
