<a href="https://colab.research.google.com/github/fernandodeeke/can2025/blob/main/gauss_elim1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center> <h1> </h1>    </center>
<center><h1>Análise Numérica</h1></center>
<center><h2>2025/1</h2></center>
<center><h3>Eliminação Gaussiana - Parte 1</h3></center>
<center><h4>Prof. Fernando Deeke Sasse - CCT, UDESC</h4></center>
<center><h3>04 de março de 2025</h3></center>

### 1.  Sistemas Lineares - Introdução

Definiremos funções em Python que realizam as operações elementares sobre linhas de uma matriz que serão úteis para resolver sistemas de equações lineares ou simplesmente, sistemas lineares.  Um [sistema linear](https://pt.wikipedia.org/wiki/Sistema_de_equações_lineares) é um conjunto de equações lineares acopladas entre por meio de variáveis $x_1,\ldots, x_n$, da forma:

\begin{align}
a_{11}x_1 + a_{12}x_2 + \cdots + a_{1n}x_n & = b_1 \\\
a_{10}x_1 + a_{22}x_2 + \cdots + a_{2n}x_n & = b_2 \\\
& \vdots \\\
a_{m1}x_1 + a_{m1}x_2 + \cdots + a_{mn}x_n & = b_m \\\
\end{align}

Em notação matricial o sistema linear de $n$ equações  e $n$ incógnitas é representado na forma
 $A X= B$, sendo

$$
A = \begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & & & \vdots \\\
a_{n 1} & a_{n 2} & \cdots & a_{n n} \\
\end{bmatrix}
 \ \ , \ \
X = \begin{bmatrix}
x_1 \\\ x_2 \\ \vdots \\ x_n
\end{bmatrix}
 \ \ , \ \
B = \begin{bmatrix}
b_1 \\\ b_2 \\\ \vdots \\ b_n
\end{bmatrix}
$$

O que chamamos de matriz ampliada associada ao sistema linear $AX=B$ é a matriz definida por

$$
[A|B] = \begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n}& b_{1} \\
a_{21} & a_{22} & \cdots & a_{1n}& b_{2} \\
\vdots & & & \vdots \\
a_{n1} & a_{n2} & \cdots & a_{nn} & b_{n}\\
\end{bmatrix}
$$

O método da eliminação gaussiana para sistemas lineares, que trataremos a seguir faz uso da matriz ampliada.


### 2. Eliminação Gaussiana - Introdução

O chamado método da eliminação gaussiana é o método direto mais utilizado para resolver sistemas lineares e é a base para todas as variantes de métodos de eliminação. O método descrito aqui é também chamado *eliminação gaussiana simples*, para distingui-lo de outros mais aperfeiçoados (mas computacionalmente mais lentos).  Ele consiste de duas etapas:

1. Fase de eliminação: realizamos a eliminação dos elementos abaixo da diagonal principal da matriz ampliada $[A|B]$ por meio de transformações elementares sobre matrizes, até obtermos a forma escalonada.
2. Retrosubstituição.

Descreveremos a seguir cada uma destas etapas:

#### (a) Fase de eliminação
Nesta fase usamos as chamadas *operações elementares sobre linhas* da matriz ampliada. A ideia é que as linhas da matriz podem ser multiplicadas por fatores, somadas entre si e trocadas de ordem, sem que a solução do correspondente sistema linear seja alterada. A ideia consiste em realizar operações elementares de modo o colocar a matriz na forma escalalonada:

$$
[A|B] = \begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n}& b_{1} \\
0 & a_{22} & \cdots & a_{2n}& b_{2} \\
\vdots & & & \vdots & \vdots \\
0 & 0 & \cdots & a_{nn} & b_{n}\\
\end{bmatrix}
$$

O correspondente sistema agora tem a forma geral:

\begin{align}
a_{11}x_1 + a_{12}x_2 + \cdots + a_{1n}x_n & = b_1 \\\
 a_{22}x_2 + \cdots + a_{2n}x_n & = b_2 \\\
& \vdots \\\
 a_{nn}x_n & = b_n \\\
\end{align}

Nesta forma a solução pode ser facilmente obtida por meio do processo de retrosubstituição, descrito a seguir:

#### (b) Fase de retrosubstituição

Começamos a resolver a corresponde última equação do sistema reduzido, ou seja,

$$
x_n=\frac{b_n}{a_{nn}}\,.
$$

Consideremos agora o estágio da retrosubstituição onde $x_n, x_{n-1}, \ldots , x_{k+1} $ já foram computados e devemos computar $x_k$,  a partir da equação $k$:

$$
a_{kk}x_k+a_{k k+1} x_{k+1}+ \cdots + a_{k n}x_n=b_k\,.
$$

Resolvendo para $x_k$ obtemos

$$
x_k=\frac{1}{a_{kk}}\left(b_k-a_{k k+1} x_{k+1}- \cdots - a_{k n}x_n\right)= \frac{1}{a_{kk}}\left(b_k-\sum_{j=k+1}^n a_{kj}x_j\right)\,.
$$

A implementação deste método em Python será abordada mais adiante. Antes disso examinaremos com mais detalhe o processo de operações elementares sobre linhas em Python.

### 3. Operações Elementares sobre Linhas

[Operações elementares sobre linhas](https://pt.wikipedia.org/wiki/Operação_elementar_(matrizes)) incluem:

1. Adicionar $\lambda$ vezes a linha $j$ à linha $i$.
2. Multiplicar a linha $i$ pelo escalar $\lambda$.
3. Trocar entre si as linhas $i$ e $j$.

Cada uma das operações elementares de linha pode ser entendida como o  resultado de uma multiplicação matricial à esquerda por uma matriz elementar.

Para adicionar $k$ vezes a linha $i$ à linha $j$ em uma matriz $A$, multiplicamos $A$ pela matriz $E$ sendo $E$ igual à matriz identidade, exceto pela componente  $E_{ij} = k$.

Por exemplo, se $A$ é a matriz ampliada dada por

$$
A = \begin{bmatrix}
6 & 1 & 2 & 3\\\
5 & 11 & -3 & 5\\\
-3 & 4 & 3 & 7
\end{bmatrix}
$$

e queremos adicionar 2 vezes a linha 2 à linha 0, então devemos calcular $E_1A$, sendo

$$
E_1 = \begin{bmatrix}
1 & 0 & 2 \\\
0 & 1 & 0 \\\
0 & 0 & 1
\end{bmatrix}
$$

De fato,

In [ ]:
import numpy as np

In [ ]:
A = np.array([[6,1,2,3],[5,11,-3,5],[-3,4,3,7]])
print(A)

[[ 6  1  2  3]
 [ 5 11 -3  5]
 [-3  4  3  7]]


In [ ]:
E1 = np.array([[1,0,2],[0,1,0],[0,0,1]])
print(E1)

[[1 0 2]
 [0 1 0]
 [0 0 1]]


In [ ]:
E1@A

array([[ 0,  9,  8, 17],
       [ 5, 11, -3,  5],
       [-3,  4,  3,  7]])

Suponhamos que queremos permutar as linhas 2 e 1 da matriz $A$. Para isso basta calcular $E_2A$, com

$$
E_2 = \begin{bmatrix}
1 & 0 & 0 \\\
0 & 0 & 1 \\\
0 & 1 & 0
\end{bmatrix}\,.
$$

De fato,

In [ ]:
E2 = np.array([[1,0,0],[0,0,1],[0,1,0]])
print(E2)

[[1 0 0]
 [0 0 1]
 [0 1 0]]


In [ ]:
E2 @ A

array([[ 6,  1,  2,  3],
       [-3,  4,  3,  7],
       [ 5, 11, -3,  5]])

### 4. Funções em Python para as Operações Elementares sobre Linhas

A seguir definiremos as funções que implementam as operações elementares sobre linhas por meio de multiplicação matricial.

#### 4.1 Soma de linhas

Definimos uma função chamado soma_linhas que tem como entradas a matriz $A$, índices $k$, $i$ e $j$ e como saída a matriz que resulta da soma da linha $j$ multiplicada por $k$ com a linha $i$. Se $i=i$, basta definir $E_{ii}=k+1$.

In [ ]:
def soma_linha(A,k,i,j):
    "Soma k vezes a linha j à linha i na matriz A"
    n=A.shape[0]
    E=np.eye(n)
    if i == j:
        E[i,i] = k+1
    else:
        E[i,j] = k
    return E@A

Testemos a função para a redução de uma matriz à forma triangular superior.

In [ ]:
M=np.array([[1,2,3,8],[4,5,6,10], [7,8,4,11]])
M

array([[ 1,  2,  3,  8],
       [ 4,  5,  6, 10],
       [ 7,  8,  4, 11]])

In [ ]:
M1 = soma_linha(M,-4,1,0)
M2 = soma_linha(M1,-7,2,0)
M3 = soma_linha(M2,-2,2,1)
M3

array([[  1.,   2.,   3.,   8.],
       [  0.,  -3.,  -6., -22.],
       [  0.,   0.,  -5.,  -1.]])

#### 4.2 Reescala de linhas

Vamos definir uma função chamada escala_linha que tem como entradas a matriz $A$ e os índices $k$ e $i$ e como saída a matriz que resulta da multiplicação por $k$ da linha $i$ de $A$.

In [ ]:
def escala_linha(A,k,i):
    "Multiplica a linha i por k na matriz A"
    n=A.shape[0]
    E=np.eye(n)
    E[i,i] = k
    return E@A

Consideremos novamente a matriz $M$:

In [ ]:
M

array([[ 1,  2,  3,  8],
       [ 4,  5,  6, 10],
       [ 7,  8,  4, 11]])

Multipliquemos a segunda linha por 1/4:

In [ ]:
escala_linha(M,1/4,1)

array([[ 1.  ,  2.  ,  3.  ,  8.  ],
       [ 1.  ,  1.25,  1.5 ,  2.5 ],
       [ 7.  ,  8.  ,  4.  , 11.  ]])

#### 4.3 Troca de linhas

Vamos definir uma função chamada troca_linhas que tem como entradas a matriz $A$ e os índices $i$ e $j$ e como saída a matriz resultante da troca das linhas $i$ e $j$ de $A$.

In [ ]:
def troca_linhas(A,i,j):
    "Troca as linhas i e j de A"
    n=A.shape[0]
    E=np.eye(n)
    E[i,i]=0
    E[j,j]=0
    E[i,j]=1
    E[j,i]=1
    return E@A

Consideremos novamente a matriz $M$:

In [ ]:
M

array([[ 1,  2,  3,  8],
       [ 4,  5,  6, 10],
       [ 7,  8,  4, 11]])

Troquemos a primeira pela terceira linha:

In [ ]:
troca_linhas(A,0,2)

array([[ 2.,  7.,  8.],
       [ 8.,  7., 12.],
       [ 6., 15.,  1.]])

### 5. Exemplo de Solução de um Sistema Linear com Eliminação Gaussiana

Usemos eliminação de Gauss para resolver o sistema $A X = B$, com $A$ e $B$ definidos abaixo:

In [ ]:
A = np.array([[6,15,1],[8,7,12],[2,7,8]])
print(A)

[[ 6 15  1]
 [ 8  7 12]
 [ 2  7  8]]


In [ ]:
B = np.array([[2],[14],[10]])
print(B)

[[ 2]
 [14]
 [10]]


Formemos a matriz aumentada $M$:

In [ ]:
M = np.hstack([A,B])
print(M)

[[ 6 15  1  2]
 [ 8  7 12 14]
 [ 2  7  8 10]]


Façamos agora as operações elementares sobre linhas:

In [ ]:
M1 = soma_linha(M,-M[1,0]/M[0,0],1,0)
print(M1)

[[  6.          15.           1.           2.        ]
 [  0.         -13.          10.66666667  11.33333333]
 [  2.           7.           8.          10.        ]]


In [ ]:
M2 = soma_linha(M1,-M1[2,0]/M1[0,0],2,0)
print(M2)

[[  6.          15.           1.           2.        ]
 [  0.         -13.          10.66666667  11.33333333]
 [  0.           2.           7.66666667   9.33333333]]


In [ ]:
M3 = soma_linha(M2,-M2[2,1]/M2[1,1],2,1)
print(M3)

[[  6.          15.           1.           2.        ]
 [  0.         -13.          10.66666667  11.33333333]
 [  0.           0.           9.30769231  11.07692308]]


Portanto, realizando a retrosubstituição obtemos

In [ ]:
x2 = M3[2,3]/M3[2,2]
x2

1.1900826446280992

In [ ]:
x1 = 1./M3[1,1]*(M3[1,3]-M3[1,2]*x2)
x1

0.10468319559228649

In [ ]:
x0 = 1./M3[0,0]*(M3[0,3]-M3[0,1]*x1-M3[0,2]*x2)
x0

-0.12672176308539942

Ou seja, a solução é dada por

In [ ]:
x = np.transpose(np.array([[x0,x1,x2]]))
x

array([[-0.12672176],
       [ 0.1046832 ],
       [ 1.19008264]])

Verifiquemos o resultado calculando o resíduo.

In [ ]:
A@x-B

array([[0.],
       [0.],
       [0.]])

Este resultado pode ser obtido diretamente usando o comando do numpy:

In [ ]:
x = np.linalg.solve(A,B)
print(x)

[[-0.12672176]
 [ 0.1046832 ]
 [ 1.19008264]]


### 6.  Exercício

Use eliminação gaussiana passo a passo, usando opereções elementares sobre linhas, para resolver o sistema o sistema linear $AX=B$ com

$$
A = \begin{bmatrix}
0 & 2 & 3& 5 \\
4 & -5 & 6& -3 \\
1 & 5 & 2 & 1\\
2 & -4 & 1 & 3
\end{bmatrix}\,,
\qquad
B =
\begin{bmatrix}
1  \\
-4  \\
2\\
3\\
\end{bmatrix}\,.
$$

Verifique a validade do resultado calculando o resíduo e obtenha o mesmo resultado usando o solver do numpy.
