<a href="https://colab.research.google.com/github/fernandodeeke/can2025/blob/main/Gauss_Elim_10_6_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Eliminação Gaussiana

In [1]:
import numpy as np

In [6]:
A = np.array([[6,1,2,3],[5,11,-3,5],[-3,4,3,7]])
A

array([[ 6,  1,  2,  3],
       [ 5, 11, -3,  5],
       [-3,  4,  3,  7]])

Façamos algumas operações elementares sobre linhas.

Suponhamos que fazer a operação de somar duas vezes a terceira à primeira linha:

$$
L_0\rightarrow L_0+2L_2\,.
$$

Podemos fazer isso multiplicando $A$ por uma matriz conveniente:




In [7]:
E1 = np.array([[1,0,2], [0,1,1], [0,0,1]])
E1

array([[1, 0, 2],
       [0, 1, 1],
       [0, 0, 1]])

In [10]:
A1 = E1@A
A1

array([[ 0,  9,  8, 17],
       [ 2, 15,  0, 12],
       [-3,  4,  3,  7]])

Suponhamos que queremos trocar a terceira pela segunda linha:

In [12]:
E2 = np.array([[1,0,0], [0,0,1], [0,1,0] ])
E2

array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]])

In [13]:
E2@A1

array([[ 0,  9,  8, 17],
       [-3,  4,  3,  7],
       [ 2, 15,  0, 12]])

Criemos uma função que soma linhas:

In [14]:
def sum_rows(A,k, i, j):
  # Add k time row j to row i
  n = A.shape[0]
  E = np.eye(n)
  if i == j:
    E[i,i] = k+1
  else:
    E[i,j] = k
  return E@A

In [16]:
A

array([[ 6,  1,  2,  3],
       [ 5, 11, -3,  5],
       [-3,  4,  3,  7]])

In [17]:
sum_rows(A,2,0,2)

array([[ 0.,  9.,  8., 17.],
       [ 5., 11., -3.,  5.],
       [-3.,  4.,  3.,  7.]])

Façamos um teste para escalonar uma matriz.

In [18]:
M = np.array([[1,2,3,8],[4,5,6,10], [ 7,8,4,11]])
M

array([[ 1,  2,  3,  8],
       [ 4,  5,  6, 10],
       [ 7,  8,  4, 11]])

In [20]:
M1 = sum_rows(M,-4,1,0)
M2 = sum_rows(M1,-7,2,0)
M2

array([[  1.,   2.,   3.,   8.],
       [  0.,  -3.,  -6., -22.],
       [  0.,  -6., -17., -45.]])

In [22]:
M3 = sum_rows(M2,-2,2,1)
M3

array([[  1.,   2.,   3.,   8.],
       [  0.,  -3.,  -6., -22.],
       [  0.,   0.,  -5.,  -1.]])

Suponha que queremos somente multiplicar uma linha por um escalar:

In [26]:
def scale_row(A,k,i):
  # Multiply row i by k
  n = A.shape[0]
  E = np.eye(n)
  E[i,i] = k
  return E@A

Troca de linhas:

In [27]:
def swap_rows(A,i,j):
  # Swap rows i and j
  n = A.shape[0]
  E = np.eye(n)
  E[i,i] = 0
  E[j,j] = 0
  E[i,j] = 1
  E[j,i] = 1
  return E@A

In [28]:
M

array([[ 1,  2,  3,  8],
       [ 4,  5,  6, 10],
       [ 7,  8,  4, 11]])

In [29]:
swap_rows(M,0,2)

array([[ 7.,  8.,  4., 11.],
       [ 4.,  5.,  6., 10.],
       [ 1.,  2.,  3.,  8.]])

**Exercício**. Resolva o sistema linear abaixo usando os comandos acima para executar as operações elementares sobre linhas:

In [30]:
A = np.array([[6,15,1],[8,7,12], [2,7,8]])
A

array([[ 6, 15,  1],
       [ 8,  7, 12],
       [ 2,  7,  8]])

In [33]:
B = np.array([[2],[14],[10]])
B

array([[ 2],
       [14],
       [10]])

In [34]:
# Matriz aumentada:
M = np.hstack((A,B))
M

array([[ 6, 15,  1,  2],
       [ 8,  7, 12, 14],
       [ 2,  7,  8, 10]])

In [37]:
# Usando numpy:
X = np.linalg.solve(A,B)
X

array([[-0.12672176],
       [ 0.1046832 ],
       [ 1.19008264]])

In [40]:
np.dot(A,X)-B

array([[0.],
       [0.],
       [0.]])

In [42]:
# Se o sistema for muito grande, calcule a norma:
res = np.dot(A,X)-B
np.linalg.norm(res)

np.float64(0.0)