<a href="https://colab.research.google.com/github/fernandodeeke/can2025/blob/main/intro_python1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1> </h1>
<center>
<h2>Cálculo 2 </h2>
<h3>Fernando Deeke Sasse</h3>
<h1> Introdução ao Python </h1>
</center>

Carreguemos a biblioteca fundamental do Python:

In [1]:
import numpy as np

In [4]:
A = np.array([1.2, 3.9, 3., 2.])
A

array([1.2, 3.9, 3. , 2. ])

In [5]:
A**2

array([ 1.44, 15.21,  9.  ,  4.  ])

In [6]:
np.sqrt(A)

array([1.09544512, 1.97484177, 1.73205081, 1.41421356])

In [7]:
np.sin(A)

array([ 0.93203909, -0.68776616,  0.14112001,  0.90929743])