<a href="https://colab.research.google.com/github/fernandodeeke/can2025/blob/main/LU_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center><h1></h1>
<center><h1>Cálculo Numérico CAN0001</h1></center>
<center><h2>2025/1</h2></center>
<center><h3>Fernando Deeke Sasse</h3></center>
<center><h3>CCT - UDESC</h3></center>
<center><h2>Fatoração LU</h2></center>

### 1. Fatoração LU  - Introdução

É possível mostrar q qualquer matriz não singular $\mathbf{A}$ pode ser decomposta uma matriz triangular inferior $\mathbf{L}$, e matriz triangular superior $\mathbf{U}$, ou seja,

$$ A = LU $$

com

\begin{equation}
\mathbf{A} = \begin{pmatrix}a_{11}&a_{12}&\ldots&a_{1n}\\a_{21}&\ddots& &a_{2n}\\\vdots& &\ddots& \vdots\\a_{n1}&...&...&a_{nn}\end{pmatrix},
\mathbf{L} = \begin{pmatrix}l_{11}&l_{12}&\ldots&l_{1n}\\l_{21}&\ddots& &l_{2n}\\\vdots& &\ddots& \vdots\\l_{n1}&...&...&l_{nn}\end{pmatrix},\\
\mathbf{U} = \begin{pmatrix}u_{11}&u_{12}&\ldots&u_{1n}\\u_{21}&\ddots& &u_{2n}\\\vdots& &\ddots& \vdots\\u_{n1}&...&...&u_{nn}\end{pmatrix}.
\end{equation}

O procedimento, como veremos a seguir, consiste no uso da eliminação gaussiana.
Este é um dos métodos mais utilizados na prática para sistema lineares não esparsos (sistemas esparsos, ou seja com uma matriz de coefientes com a maior parte de componentes nulas, serão tratados mais adiante por meio de métodos iterativos.

A ideia consiste no seguinte. Uma vez obtida a fatoração na forma $A = LU$ o sistema $AX=B$ passa a ser ter a forma $LUX=B$. Definindo $Y=UX$ o sistema agora tem a forma $LY=B$. Este sistema pode ser resolvido para $Y$ usando substituição avançada. Ou seja, determinamos $y_1$ a partir da primeira linha, $y_2$ a partir da segunda, e assim por diante. Uma vez obtido $Y$ o próximo passo consiste em resolver o sistema $UX=Y$, que pode ser resolvido para $X$ usando retrosubstituição.

A vantagem deste procedimento torna-se aparente quando temos que resolver diversos sistemas de equações que têm a mesma matriz de coeficientes,

$$
AX_1=B_1, \qquad AX_2=B_2,\quad \cdots \quad,\, AX_N=B_N\,.
$$

Outra aplicação consiste na inversão de matrizes. Para inverter uma matriz $A$, de ordem $n \times n$, devemos encontrar uma matriz inversa de $A$, denominada $A^{-1}$, que satisfaz a

$$
A A^{-1} = I,
$$
sendo $I$ a matriz identidade, $n \times n$.

Reescrevamos $I$ e $A^{-1}$ em termos de matrizes coluna, ou seja,  $I = [e_1 | e_2 | \cdots e_n]$, e  $ A^{-1} = [v_1 | v_2 | \cdots v_n]$. A determinação da matriz inversa agora consiste na resolução de $n$ sistemas lineares da forma

$$
A v_1 = e_1\,, \quad Av_2 = e_2\,,\cdots \,,\, Av_n=e_n\,.
$$

A eliminação Gaussiana tem um custo operacional da ordem de $O(n^3)$ operações. Este é o mesmo custo da operação de fatoração de matrizes, com a diferença de que na fatoração LU a operação é feita somente uma vez no caso de termos que resolver vários sistemas com a mesma matriz de coeficientes. O custo das operações de substituição atrasada (retrosubstituição) e avançada é $O(n^2)$.

A fatoração LU não é única, mas há três tipos que são mais utilizados:

1. Fatoração de Doolittle: $l_1 = l_2 = \ldots = l_n = 1$.
2. Fatoração de Crout: $u_1 = u_2 = \ldots = u_n = 1$.
3. Fatoração de Cholesky: $L = U^T$ (quando a matriz $A$ é simétrica).

Veremos a seguir o procedimento computacional para a fatoração de Doolittle.




### 2. Procedimento operacional para fatoração de Doolittle

Simplesmente realizamos a eliminação gaussiana sobre a matriz A para obter uma matriz triangular superior. Os multiplicadores $m_{ij}$ utilizados na eliminação dos elementos $a_{ij}$ de $A$ são exatamente as componentes abaixo da diagonal da matriz $L$, ou seja, $l_{ij}=m_{ij}$.

Vejamos um exemplo, executando o procedimento passo a passo.

Usaremos uma função que realiza operações elementares de linha:

In [ ]:
def soma_linha(A,k,i,j):
    "Soma k vezes a linha j à linha i na matriz A"
    n=A.shape[0]
    E=np.eye(n)
    if i == j:
        E[i,i] = k+1
    else:
        E[i,j] = k
    return E@A

In [ ]:
import numpy as np

Consideremos o sistema $AX=B$ com

In [ ]:
A = np.array([[2.,4.,5.], [5.,9.,-3.],[3.,5.,1.]])
A

array([[ 2.,  4.,  5.],
       [ 5.,  9., -3.],
       [ 3.,  5.,  1.]])

In [ ]:
B = np.array([[2,3,1]])
B.T

array([[2],
       [3],
       [1]])

Realizemos o procedimento de eliminação gaussiana armazenando os multiplicadores.

In [ ]:
m10 = 5./2.
A1 = soma_linha(A,-m10,1,0)
A1

array([[  2. ,   4. ,   5. ],
       [  0. ,  -1. , -15.5],
       [  3. ,   5. ,   1. ]])

In [ ]:
m20 = 3./2.
A2 = soma_linha(A1,-m20,2,0)
A2

array([[  2. ,   4. ,   5. ],
       [  0. ,  -1. , -15.5],
       [  0. ,  -1. ,  -6.5]])

In [ ]:
m21 = 1.
A3 = soma_linha(A2,-m21,2,1)
A3

array([[  2. ,   4. ,   5. ],
       [  0. ,  -1. , -15.5],
       [  0. ,   0. ,   9. ]])

A matriz escalonada é a matriz U

In [ ]:
U = A3
U

array([[  2. ,   4. ,   5. ],
       [  0. ,  -1. , -15.5],
       [  0. ,   0. ,   9. ]])

A matriz L é aquela com os multiplicadores abaixo da diagonal:

In [ ]:
L=np.diag(np.array([1.,1.,1.]))
L[1,0]=m10
L[2,0]=m20
L[2,1]=m21
L

array([[1. , 0. , 0. ],
       [2.5, 1. , 0. ],
       [1.5, 1. , 1. ]])

Podemos verificar que realmente $LU=A$:

In [ ]:
L@U-A

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Definimos a função para substituição avançada:

In [ ]:
def GaussAv(a, b):
    n = len(b)
    x = np.zeros_like(b, dtype=float)  # Garante o mesmo tipo de b
    for k in range(n):
        x[k] = (b[k] - np.dot(a[k, :k], x[:k]))
    return x.reshape(-1, 1)

Resolvemos $LY=B$:

In [ ]:
Y = GaussAv(L,B.T)
Y

array([[ 2.],
       [-2.],
       [ 0.]])

Para resolver $UX=Y$ devemos usar a retrosubstituição:

In [ ]:
def GaussRetro(a, b):
    n = len(b)
    x = np.zeros_like(b)
    # Retrosubstituição
    for k in range(n-1, -1, -1):
        x[k] = (b[k] - np.dot(a[k, k+1:], x[k+1:])) / a[k, k]
    return x.reshape(-1, 1)

In [ ]:
X=GaussRetro(U,Y)
X

array([[-3.],
       [ 2.],
       [ 0.]])

Podemos verificar este resultado:

In [ ]:
A@X-B.T

array([[0.],
       [0.],
       [0.]])

### 3.  Pseudocódigo para a fatoração LU de Doolittle

Consideremos as matrizes:

\begin{equation}
\mathbf{A} = \begin{pmatrix}a_{11}&a_{12}&\ldots&a_{1n}\\a_{21}&\ddots& &a_{2n}\\\vdots& &\ddots& \vdots\\a_{n1}&...&...&a_{nn}\end{pmatrix},
\mathbf{L} = \begin{pmatrix}1&l_{12}&\ldots&0\\l_{21}&\ddots& &l_{2n}\\\vdots& &\ddots& \vdots\\0&...&...&1\end{pmatrix},\\
\mathbf{U} = \begin{pmatrix}u_{11}&u_{12}&\ldots&u_{1n}\\0&\ddots& &u_{2n}\\\vdots& &\ddots& \vdots\\0&...&...&u_{nn}\end{pmatrix}
\end{equation}

Podemos resumir o procedimento passo a passo para efetuar a fatoração Doolittle  LU de $A$ da no seguinte pseudocódigo:

| Passos | |
|--: | :-- |
| 1. | Inicialize $\mathbf{L}$ como uma matriz identidade, $\mathbf{I}$ de dimensão $n\times n$ e $\mathbf{U = A}$.
| 2. | Para $i = 1, \ldots, n$ realize passo 3
| 3. | $\phantom{--}$ For $j=i+1, \ldots, n$ realize passos 4-5
| 4. | $\phantom{----}$ Faça $l_{ji}=u_{ji}/u_{ii}$
| 5. | $\phantom{----}$ Determine $U_j = (U_j-l_{ji}U_i)$ (sendo $U_i, U_j$ as linhas $i$ e $j$ da matriz $\mathbf{U}$, respectivamente.)

### 4. Função em Python para fatoração de Doolittle
Uma forma de implementar o pseudocódigo acima é o seguinte:

In [ ]:
def LU(A):
    n = A.shape[0]
    L = np.eye(n, dtype=float)  # L começa como matriz identidade
    U = np.zeros_like(A, dtype=float)  # U começa como matriz nula

    for k in range(n):  # Itera pelas colunas
        # Calcula a linha k de U (parte triangular superior)
        # Só precisamos calcular a partir da diagonal (k,k) pois os elementos antes são zero
        for j in range(k, n):
            U[k, j] = A[k, j] - np.dot(L[k, :k], U[:k, j])
        if k < n - 1:
            # Calcula os multiplicadores e armazena em L (abaixo da diagonal)
            # Só calculamos para i > k pois os elementos acima da diagonal são zero
            for i in range(k+1, n):
                L[i, k] = (A[i, k] - np.dot(L[i, :k], U[:k, k])) / U[k, k]
    return L, U

### 5. Explicação Passo a Passo da Fatoração LU (Doolittle)

A fatoração LU decompõe a matriz $A$ $n\times n$  em $A=LU$:
- `L` (triangular **inferior** com diagonal `1`)
- `U` (triangular **superior**)

A cada iteração $k$, atualizamos a linha $k$ de $U$ e a coluna $k$ de $L$:

---

#### **Iteração `k = 0` (Primeira linha e coluna)**
1. **Cálculo de `U[0, :]`**:
   - `U[0, j] = A[0, j] - (produto vazio) = A[0, j]` para `j ≥ 0`.
   - Como `L[0, :0]` (antes da coluna 0) é vazio, o produto interno é zero.
   - **Resultado**:  
     $$
     U[0, :] = \begin{bmatrix} A_{00} & A_{01} & A_{02} & \cdots \end{bmatrix}
     $$

2. **Cálculo de `L[:, 0]`** (abaixo da diagonal):

   $$
   L[i, 0] = \frac{A[i, 0]}{U[0, 0]},, \quad i > 0.
   $$

   **Exemplo**:  
     $$
     L[1, 0] = \frac{A_{10}}{U_{00}}, \quad L[2, 0] = \frac{A_{20}}{U_{00}}, \quad \dots
     $$

---

#### **Iteração `k = 1` (Segunda linha e coluna)**
1. **Cálculo de `U[1, 1:]`**:
   $$ U[1, j] = A[1, j] - L[1, 0] \cdot U[0, j]\,\quad j ≥ 1.$$
   - **Exemplo**:  
     $$
     U_{11} = A_{11} - L_{10} \cdot U_{01}, \quad U_{12} = A_{12} - L_{10} \cdot U_{02}, \quad \dots
     $$

2. **Cálculo de `L[:, 1]`** (abaixo da diagonal):
   $$ L[i, 1] = \frac{A[i, 1] - L[i, 0] \cdot U[0, 1]}{U[1, 1]} \,,\quad i > 1$$
**Exemplo**:  
     $$
     L_{21} = \frac{A_{21} - L_{20} \cdot U_{01}}{U_{11}}, \quad L_{31} = \frac{A_{31} - L_{30} \cdot U_{01}}{U_{11}}, \quad \dots
     $$

---

#### **Iteração `k = 2` (Terceira linha e coluna)**
1. **Cálculo de `U[2, 2:]`**:
   $$
   U[2, j] = A[2, j] - (L[2, 0] \cdot U[0, j] + L[2, 1] \cdot U[1, j])\,,\quad j \geq 2
   $$
**Exemplo**:  
     $$
     U_{22} = A_{22} - (L_{20} \cdot U_{02} + L_{21} \cdot U_{12})
     $$

3. **Cálculo de `L[:, 2]`** (abaixo da diagonal):
   $$
   L[i, 2] = \frac{A[i, 2] - (L[i, 0] \cdot U[0, 2] + L[i, 1] \cdot U[1, 2])}{U[2, 2]} \,,\quad i > 2
   $$

---

#### **Padrão Geral para Iteração `k`**
1. **Linha `k` de `U`**:
   $$
   U_{kj} = A_{kj} - \sum_{m=0}^{k-1} L_{km} \cdot U_{mj} \quad \text{para} \quad j \geq k
   $$

2. **Coluna `k` de `L`** (abaixo da diagonal):
   $$
   L_{ik} = \frac{A_{ik} - \sum_{m=0}^{k-1} L_{im} \cdot U_{mk}}{U_{kk}} \quad \text{para} \quad i > k
   $$

---

### **Observações**
- **`L`**: Sempre tem diagonal `1` e zeros acima da diagonal.
- **`U`**: Sempre tem zeros abaixo da diagonal.
- Os somatórios são **vazios** para `k = 0`, simplificando os cálculos iniciais.


### 6. Exemplos

Testemos a função:

In [ ]:
A = np.array([[3,6,8], [5,4,-3],[3,5,1]],dtype = float)
A

array([[ 3.,  6.,  8.],
       [ 5.,  4., -3.],
       [ 3.,  5.,  1.]])

In [ ]:
L, U = LU(A)
print(L)
print(U)

[[1.         0.         0.        ]
 [1.66666667 1.         0.        ]
 [1.         0.16666667 1.        ]]
[[  3.           6.           8.        ]
 [  0.          -6.         -16.33333333]
 [  0.           0.          -4.27777778]]


In [ ]:
A

array([[ 3.,  6.,  8.],
       [ 5.,  4., -3.],
       [ 3.,  5.,  1.]])

Verifiquemos o resultado:

In [ ]:
L@U-A

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00, -1.77635684e-15],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

Podemos agora escrever a função completa:

In [ ]:
def lu_solve1(A, b):
    L, U = LU(A)
    y = GaussAv(L, b)
    return GaussRetro(U, y)

Testemos a função no mesmo sistema usado anteriormente:

In [ ]:
A = np.array([[2.,4.,5.], [5.,9.,-3.],[3.,5.,1.]])
B = np.transpose(np.array([[2,3,1]]))

In [ ]:
X =lu_solve(A,B)
X

array([[-3.],
       [ 2.],
       [ 0.]])

que é o resultado esperado. De fato,

In [ ]:
np.allclose(A @ X - B, np.zeros((3,)))

True

Vejamos o tempo aproximado de CPU para realizar este cálculo.

In [ ]:
%timeit lu_solve(A,B)

20.9 μs ± 102 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


### 7. Função geral LU

Podemos juntar as três funções anteriores (modificando os procedimentos de substituição) para obter uma função da seguinte forma:

In [ ]:
import numpy as np

def lu_solve_2(A, B):
    """
    Resolve o sistema AX = B usando fatoração LU de Doolittle (sem pivoteamento).

    Parâmetros:
        A: Matriz de coeficientes (n x n)
        B: Matriz/Vetor de termos independentes (n x m) ou (n,)

    Retorna:
        X: Solução do sistema (n x m) ou (n,)
    """
    A = np.array(A, dtype=float)
    B = np.array(B, dtype=float)

    # Verifica se A é quadrada
    if A.shape[0] != A.shape[1]:
        raise ValueError("A matriz A deve ser quadrada.")

    n = A.shape[0]

    # Fatoração LU (Doolittle)
    L = np.eye(n)  # Inicializa L como identidade
    U = np.zeros((n, n))  # Inicializa U como zeros

    for k in range(n):
        # Calcula a linha k de U
        U[k, k:] = A[k, k:] - L[k, :k] @ U[:k, k:]

        # Calcula a coluna k de L (após a diagonal)
        if k < n - 1:
            L[k+1:, k] = (A[k+1:, k] - L[k+1:, :k] @ U[:k, k]) / U[k, k]

    # Verifica se U tem pivôs nulos (matriz singular)
    if np.any(np.diag(U) == 0):
        raise ValueError("Matriz singular (pivô zero detectado). Não é possível resolver o sistema.")

    # Resolve LY = B (substituição avançada)
    Y = np.zeros_like(B)
    for i in range(n):
        Y[i] = B[i] - L[i, :i] @ Y[:i]

    # Resolve UX = Y (retrosubstituição)
    X = np.zeros_like(Y)
    for i in range(n-1, -1, -1):
        X[i] = (Y[i] - U[i, i+1:] @ X[i+1:]) / U[i, i]

    return X

Testemos a função em um sistema aleatório:

In [ ]:
np.random.seed(22222)
N = 4
A = np.random.rand(N,N)
B = np.random.rand(N,1)

In [ ]:
X =lu_solve2(A,B)
X

array([[-0.05013332],
       [ 0.68742662],
       [ 0.4035997 ],
       [ 0.37803803]])

Verifiquemos o resultado:

In [ ]:
np.allclose(A @ X - B, np.zeros((4,)))

True

ou

In [ ]:
np.linalg.norm(res, ord=np.inf) # maior componente do vetor

2.220446049250313e-16

Calculemos o tempo de CPU para a realização do cálculo:

In [ ]:
%timeit lu_solve2(A,B)

23.8 μs ± 73.3 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [ ]:
np.random.seed(22222) #use os primeiros 5 números do seu cpf
N = 100
A = np.random.rand(N,N)
B = np.random.rand(N,1)

### 8. Exercícios

**1.** Resolva manualmente o sistema $AX = B$ com

In [ ]:
A = np.array([[0.,3.,6.,1.], [1.,5.,-5.,6],[4.,7.,-1.,5.],[-2., 4., 9., -3]])
B = np.transpose(np.array([[-2.,4.,2.,5.]]))

**2.** Resolva o sistema acima manualmente, mas seguindo todos os passos do algoritmo, conforme explicado acima.

**3.** Teste o algoritmo LU para sistemas grandes (use um sistema aleatório com mais de 1000 equações). Verifique o tempo de CPU utilizado.