<a href="https://colab.research.google.com/github/fernandodeeke/can2025/blob/main/matrix_intro_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center><h1><center></h1>
<center><h1>Numerical Analysis<center></h1>
<center><h2>2025/1</h2></center>
<center><h3>Fernando Deeke Sasse</h3></center>
<center><h3>CCT - UDESC</h3></center>
<center><h2>Introduction to Matrix Operations</h2></center>

###  1.  Matrices as 2-dimensional arrays

We will see that matrices in python can be represented by 2-dimensional arrays. We will use arrays defined in the numpy library

In [ ]:
import numpy as np
import numpy.linalg as LA

We initially define a particular case of matrix, which is a line vector. For instance

In [ ]:
a= np.array([1,3,-2,1])
a

array([ 1,  3, -2,  1])

To see the contents of the array we use print:

In [ ]:
print(a)

[ 1  3 -2  1]


A vector is a 1-dimensional array:

In [ ]:
a.ndim

1

The names after the period in a variable are *attributes*. The number of array elements is given by:

In [ ]:
a.size

4

In [ ]:
a.shape

(4,)

We now define an array, for example, a 3 x 3 array:

In [ ]:
M=np.array([[1,3,4],[4,3,1],[5,8,1]])
print(M)

[[1 3 4]
 [4 3 1]
 [5 8 1]]


In [ ]:
M.size

9

In [ ]:
M.shape

(3, 3)

Matrices are 2-dimensional arrays, since any of its components can be specified in terms of a pair of numbers (Note that the indexes of an array start at 0):

In [ ]:
M[0,1]

The rows and columns are called *axis* in Python. Here we find the dimension of any array:

In [ ]:
M.ndim

The size of the array is given by:

In [ ]:
M.size

9

Its shape is

In [ ]:
M.shape

(3, 3)

Let's select the first column of $M$ to generate a 1D array:

In [ ]:
col1=M[:,0]
print(col1)

[1 4 5]


We can turn this row vector into a column vector:

In [ ]:
col1L=col1.reshape(3,1)
print(col1L)

[[1]
 [4]
 [5]]


Consider the vectors $\mathbf{u}=(3,4,2)$ and $\mathbf{v}=(-1,2,-1)$. The scalar product $\mathbf{u}\cdot \mathbf{v}$ is given by

In [ ]:
u = np.array([3,4,2])
v = np.array([-1,2,-1])
np.dot(u,v)

np.int64(3)

The vector product $\mathbf{u} \times \mathbf{v}$ is given by

In [ ]:
np.cross(u,v)

array([-8,  1, 10])

The Frobenius (or Euclidean) norm of a vector $\mathbf{u}=(u_1,\ldots,u_n)$ is defined by
$$
|\mathbf{u}|=\left[\sum\limits_{i=1}^{n}|u_i|^2\right]^{1/2}
$$
In Python:

In [61]:
u = np.array([4,-6,1])
u

array([ 4, -6,  1])

The Euclidean norm of u is given by:

In [62]:
LA.norm(u)

np.float64(7.280109889280518)

The so-called "infinite norm" of a vector is defined as the largest magnitude among the components:

$$
|\mathbf{u}|_{\infty}=\max_i\{{|u_i|},i=1,\ldots,n\}
$$

In Python,

In [63]:
LA.norm(u, np.inf)

np.float64(6.0)

The infinite standard is the most widely used in numerical computing.

**Example 1**. Let us calculate the projection of the vector $\mathbf{u}$ in the direction of $\mathbf{v}$.

We must calculate the expression

$$
\mathbf{u}_{\mathbf{v}}=\left(\frac{\mathbf{u}\cdot\mathbf{v}}{|\mathbf{v}|^2}\right)\mathbf{v}
$$

In Python,

In [64]:
uv = (np.dot(u,v)/np.dot(v,v))*v
uv

array([ 2.83333333, -5.66666667,  2.83333333])

### 2. Matrix operations

Let us define a 3 x 3 matrix M:

In [65]:
M=np.array([[-1,3,7],[2,3,1],[9,1,3]])
print(M)

[[-1  3  7]
 [ 2  3  1]
 [ 9  1  3]]


To raise each element to the square we can proceed as follows:

In [66]:
M*M

array([[ 1,  9, 49],
       [ 4,  9,  1],
       [81,  1,  9]])

or

In [67]:
M**2

array([[ 1,  9, 49],
       [ 4,  9,  1],
       [81,  1,  9]])

Matrix multiplication is done with the @ operator:

In [68]:
M@M

array([[70, 13, 17],
       [13, 16, 20],
       [20, 33, 73]])

Special matrices:

In [69]:
I3=np.eye(3) #identity
I3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [70]:
Ones3=np.ones([3,3]) #ones
Ones3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [71]:
Zeros3=np.zeros([3,3]) #ones
Zeros3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Let

In [72]:
A = np.array([[-3,1,4,3],[3,1,6,5],[-5,3,7,1],[4,2,3,4]])
A

array([[-3,  1,  4,  3],
       [ 3,  1,  6,  5],
       [-5,  3,  7,  1],
       [ 4,  2,  3,  4]])

and

In [73]:
M = np.array([[13,-8,6,4],[3,1,6,5],[1,0,3,2],[1,3,8,-2]])
M

array([[13, -8,  6,  4],
       [ 3,  1,  6,  5],
       [ 1,  0,  3,  2],
       [ 1,  3,  8, -2]])

Let's say we want to calculate $C=2I+4A-AM$. We proceed as follows:

In [74]:
I4=np.eye(4)
I4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [75]:
C=2*I4+4*A-A@M
C

array([[ 19., -30.,  -8.,  17.],
       [-41.,  14., -58.,   1.],
       [ 28., -34.,  13.,  -3.],
       [-49.,  26., -65.,  -6.]])

Let's say we want to calculate $C=2I+4A-AM^5$. We could certainly write

In [76]:
C=2*I4+4*A-A@M@M@M@M@M
C

array([[  209886.,  -215471.,   -60778.,   -23058.],
       [-1396780.,   969721.,  -594440.,  -165828.],
       [  442705.,  -408763.,   -30857.,   -32952.],
       [-1556217.,  1100530.,  -619161.,  -173158.]])

However it is simpler to use the array potentiation operation (not defined by a simple symbol in Python). We must load a command from linear algebra to the numpy library called matrix_power:

In [77]:
from numpy.linalg import matrix_power as mpow

Note that

In [78]:
mpow(M,2)

array([[ 155, -100,   80,   16],
       [  53,   -8,   82,   19],
       [  18,   -2,   31,    6],
       [  28,  -11,   32,   39]])

In [79]:
M@M

array([[ 155, -100,   80,   16],
       [  53,   -8,   82,   19],
       [  18,   -2,   31,    6],
       [  28,  -11,   32,   39]])

Returning to our problem, we can now write

In [80]:
C=2*I4+4*A-A@mpow(M,5)
C

array([[  209886.,  -215471.,   -60778.,   -23058.],
       [-1396780.,   969721.,  -594440.,  -165828.],
       [  442705.,  -408763.,   -30857.,   -32952.],
       [-1556217.,  1100530.,  -619161.,  -173158.]])

If $M$ is given by

In [ ]:
M

array([[13, -8,  6,  4],
       [ 3,  1,  6,  5],
       [ 1,  0,  3,  2],
       [ 1,  3,  8, -2]])

we can get the transposed matrix of M:

In [ ]:
M.T

array([[13,  3,  1,  1],
       [-8,  1,  0,  3],
       [ 6,  6,  3,  8],
       [ 4,  5,  2, -2]])

Note that $M M^T$ must be a symmetric matrix. Indeed:

In [ ]:
M@M.T

array([[285,  87,  39,  29],
       [ 87,  71,  31,  44],
       [ 39,  31,  14,  21],
       [ 29,  44,  21,  78]])

Let's calculate the inverse $M^{-1}$ of $M$:

In [ ]:
LA.inv(M)

array([[ 0.06498952,  0.36897275, -1.00209644,  0.05031447],
       [-0.03563941,  0.50733753, -1.1278826 ,  0.06918239],
       [-0.00209644, -0.20545073,  0.58071279,  0.06289308],
       [-0.0293501 ,  0.12368973,  0.12997904, -0.11949686]])

The trace of the matrix $M$ (sum of the diagonal elements) is given by

In [ ]:
np.trace(M)

np.int64(15)

The determinant is given by:

In [ ]:
LA.det(M)

np.float64(-476.9999999999997)

Here we generate a Boolean matrix:

In [ ]:
Mb = M>=5
Mb

array([[ True, False,  True, False],
       [False, False,  True,  True],
       [False, False, False, False],
       [False, False,  True, False]])

We can find the elements of $M$ that are bigger or equal to 5:

In [ ]:
print(M[M>=5])

[13  6  6  5  8]


In [ ]:
M

array([[13, -8,  6,  4],
       [ 3,  1,  6,  5],
       [ 1,  0,  3,  2],
       [ 1,  3,  8, -2]])

Here we form a vector formed by adding row-vectors of $M$:

In [ ]:
np.sum(M,axis=0)

array([18, -4, 23,  9])

We can do the same with columns:

In [ ]:
np.sum(M,axis=1)

array([15, 15,  6, 10])

We can sum all elements

In [ ]:
np.sum(M)

np.int64(46)

The Frobenius norm of a matrix $A=[a_{ij}]$ of order $m \times n$ is defined by

$$
|A|_F=
\left[
\sum\limits_{i=1}^{m}
\sum\limits_{j=1}^{n}
|a_{ij}|^2
\right]^{1/2}
$$

In Python,

In [81]:
A = np.array([[1,  1,  2],[ 0,  -1,  -1],[ 2,  1,  0]])
A

array([[ 1,  1,  2],
       [ 0, -1, -1],
       [ 2,  1,  0]])

In [82]:
LA.norm(A,'fro')

np.float64(3.605551275463989)

The infinite norm of an array $A=[a_{ij}]$ of order $m \times n$ is often used in iterative process stop criteria is defined as the maximum value of the absolute sum of each row

$$
|A|_{\infty}= \max_{1\leq i\leq m}\sum_{j}^n|a_{ij}|\,.
$$

In Python,

In [ ]:
LA.norm(A, np.inf)

np.float64(4.0)

Note that when the type of norm is not specified the default result is the Frobenius norm:

In [ ]:
LA.norm(A)

np.float64(3.605551275463989)

Eigenvalues and eigenvectors of a matrix can be found in the following way:

In [ ]:
A = np.array([[3,5,2],[6,3,2],[-2,5,7]])

In [ ]:
eigval, eigvect = LA.eig(A)

In [ ]:
eigval

array([-2.40312424,  5.        , 10.40312424])

In [ ]:
eigvect

array([[ 0.48840086, -0.41684393,  0.56185538],
       [-0.72313844, -0.47639307,  0.60715489],
       [ 0.48840086,  0.77413873,  0.56185538]])

Note that the eigenvectors are the columns of the above matrix. The third eigenvector is given, for example, by

In [ ]:
eigvect[:,2]

We can check that  $det(C-I\lambda)=0$ is satisfied for all eigenvalues:

In [ ]:
for i in range(3):
    print(LA.det(A-eigval[i]*np.eye(3)))

Also, we can check that $Av_i=\lambda_i v_i$ is satisfied for all eigenvalues and eigenvectors:

In [ ]:
for i in range(3):
    print(A@eigvect[:,i]-eigval[i]*eigvect[:,i])


### 3. Exercises

**1**. Calculate the area of a triangle of vertices $(-1,3,2)$, $(3,4,-1)$, and $(3,5,1)$. Suggestion: Use the geometric interpretation of the vector product.

**Solution**. By defining the position vectors $a = (-1,2,3)$, $b= (3,4,-1)$ and $c=(3,5,1)$, and defining the vectors $u=b-a$ and $v=c-a$, the area of the triangle defined by these points can be calculated by

$$
A = \frac{1}{2}\left|u \times v \right|,.
$$

Let's do this calculation in Python.

In [ ]:
import numpy as np
import numpy.linalg as LA

In [ ]:
a = np.array([-1,3,3])
b = np.array([3,4,-1])
c = np.array([3,5,1])
u = b-a
v = c-a

In [ ]:
A = 0.5*LA.norm(np.cross(u,v))
A

Therefore, the area of the triangle is approximately equal to 5.39 units of area.

**2**. Calculate the volume of the parallelepiped determined by the vectors $u=(1,5,4)$, $v=(2,4,1)$ and $w=(9,2,6)$.

**Solution.** The volume is given by

$$
V = |u \cdot (v \times w)|,.
$$

In python,

In [ ]:
import numpy as np
import numpy.linalg as LA

In [ ]:
u = np.array([1,5,4])
v = np.array([2,4,1])
w = np.array([9,2,6])

In [ ]:
V1 = np.cross(u,v)

In [ ]:
V2 = np.abs(np.dot(w,V1))
V2

Ou seja, 121 unidades de volume.

**3.** Verifique  que a norma de Frobenius de uma matriz
$$
M=\begin{pmatrix}
-3 & 5 & 3 \\
4 & -5 & 4 \\
1 & 9 & -2
\end{pmatrix}
$$
pode também ser dada por

$$
||\mathbf{M}||_F=\sqrt{\left(\mbox{Tr}(M M^T\right)}\,.
$$


**4.** Let be the matrices
$$ A =
\begin{pmatrix}
1 & 2 & 3 \\
4 & 3 & 6 \\
7 & 8 & 9
\end{pmatrix}\,,\qquad
B =
\begin{pmatrix}
4 & 4 & 6 \\
6 & -3 & 2 \\
1 & -2 & 3
\end{pmatrix}\,.
$$

(i) Determine $C=A^3-4AB -4I$, with $I$ being the identity matrix $3 \times 3$.

(ii) Find the eigenvalues and eigenvectors of $C$.


**5.** Let be the linear system

$$
\begin{pmatrix}
-1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{pmatrix}
\begin{pmatrix}
x  \\
y  \\
z
\end{pmatrix}
=
\begin{pmatrix}
1  \\
-4  \\
3\,.
\end{pmatrix}
$$

Solve the system by explicitly calculating the expression:

$$
\begin{pmatrix}
x  \\
y  \\
z
\end{pmatrix}= \begin{pmatrix}
-1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{pmatrix}^{-1}\begin{pmatrix}
1  \\
-4  \\
3\,
\end{pmatrix}
.
$$

Note that this is not the most efficient method for solving a linear system.