<a href="https://colab.research.google.com/github/fernandodeeke/can2025/blob/main/PLU_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center><h1> <h2></h2></h1></center>
<center><h1>Análise Numérica</h1></center>
<center><h2>2025/1</h2></center>
<center><h3>Fernando Deeke Sasse</h3></center>
<center><h3>CCT - UDESC</h3></center>
<center><h2>Fatoração PLU </h2></center>

Construiremos agora o algoritmo de fatoração LU que realiza pivotação. O método é chamado PLU, pois uma vez feita a fatoração a matriz de permutação de linhas $P$ deve ser tal que  $PA = LU$. O código abaixo é semelhante àquele para a fatoração LU.

In [10]:
import numpy as np

def PLU(A):
    n = A.shape[0]
    L = np.eye(n, dtype=float)  # L começa como matriz identidade
    U = np.zeros_like(A, dtype=float)  # U começa como matriz nula
    P = np.eye(n, dtype=float)  # P começa como matriz identidade

    # Cria uma cópia de A para não modificar a matriz original
    A = A.copy()

    for k in range(n):  # Itera pelas colunas
        # Encontra o índice da linha com o maior valor absoluto na coluna k
        max_row = np.argmax(np.abs(A[k:, k])) + k
        if A[max_row, k] == 0:
            raise ValueError("Matriz singular, não pode ser decomposta.")

        # Realiza a troca de linhas em A e P, se necessário
        if max_row != k:
            A[[k, max_row], :] = A[[max_row, k], :]
            P[[k, max_row], :] = P[[max_row, k], :]

        # Calcula a linha k de U (parte triangular superior)
        for j in range(k, n):
            U[k, j] = A[k, j] - np.dot(L[k, :k], U[:k, j])

        # Calcula os multiplicadores de L (abaixo da diagonal)
        if k < n - 1:
            for i in range(k + 1, n):
                L[i, k] = (A[i, k] - np.dot(L[i, :k], U[:k, k])) / U[k, k]

    return P, L, U

Vejamos um exemplo:

In [11]:
A = np.array([[2, -1, -2],[-4, 6, 3],[-2, -7, 8]], dtype=float)

In [25]:
P, L, U = PLU(A)
print("P:\n", P)
print("L:\n", L)
print("U:\n", U)

P:
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L:
 [[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [-0.5 -0.2  1. ]]
U:
 [[ -4.    6.    3. ]
 [  0.  -10.    6.5]
 [  0.    0.    0.8]]


Verifiquemos o reultado:

In [34]:
np.linalg.norm(P@A-L@U, ord=np.inf)

np.float64(1.1102230246251565e-16)

Expliquemos o comando:

In [ ]:
A = np.array([[2, -1, -2],[-4, 6, 3],[-2, -7, 8]], dtype=float)
for k in range(3):
    max_row = np.argmax(np.abs(A[k:, k])) + k

max_row

np.int64(2)

Vamos analisar o código passo a passo para determinar o valor de `max_row` após a execução do laço `for k in range(3)` com a matriz fornecida:

```python
A = np.array([[2, -1, -2], [-4, 6, 3], [-2, -7, 8]], dtype=float)
for k in range(3):
    max_row = np.argmax(np.abs(A[k:, k])) + k
```

A matriz $ A $ é:

$$
A = \begin{bmatrix}
2 & -1 & -2 \\
-4 & 6 & 3 \\
-2 & -7 & 8
\end{bmatrix}
$$

O laço itera sobre $ k = 0, 1, 2 $, e em cada iteração, `max_row` é atualizado com o índice da linha que contém o maior valor absoluto na subcoluna $ A[k:, k] $ (a partir da linha $ k $ até o final da coluna $ k $), ajustado pelo deslocamento $ k $. Vamos calcular isso para cada valor de $ k $:

### Iteração 1: $ k = 0 $
- Subcoluna: $ A[0:, 0] = [2, -4, -2] $ (coluna 0 inteira).
- Valores absolutos: $ |2| = 2 $, $ |-4| = 4 $, $ |-2| = 2 $.
- `np.argmax([2, 4, 2])` retorna $ 1 $ (índice do maior valor, 4).
- `max_row = 1 + 0 = 1`.

### Iteração 2: $ k = 1 $
- Subcoluna: $ A[1:, 1] = [6, -7] $ (coluna 1 a partir da linha 1).
- Valores absolutos: $ |6| = 6 $, $ |-7| = 7 $.
- `np.argmax([6, 7])` retorna $ 1 $ (índice do maior valor, 7).
- `max_row = 1 + 1 = 2`.

### Iteração 3: $ k = 2 $
- Subcoluna: $ A[2:, 2] = [8] $ (coluna 2 a partir da linha 2, apenas um elemento).
- Valor absoluto: $ |8| = 8 $.
- `np.argmax([8])` retorna $ 0 $ (único elemento).
- `max_row = 0 + 2 = 2`.

Após o laço, o valor final de `max_row` é o calculado na última iteração, ou seja, $ k = 2 $.

### Resposta
O valor de `max_row` após a execução do código é:

\[
2
\]

**Exercício.** Seja o sistema $AX=B$, sendo

$$
A = \begin{bmatrix}
1 & -1 & -2 \\
-4 & 1/2 & 3 \\
-2 & -7 & 8
\end{bmatrix}\,,\quad
B = \begin{bmatrix}
1  \\
4 \\
9  
\end{bmatrix}\,.
$$

(i) Resolva o sistema passo a passo, usando fatoração PLU, manualmente.

(ii) Resolva passo a passo, usando fatoração PLU, seguindo o algoritmo acima.

(iii) Resolva usando diretamente o algoritmo PLU.


